### ISSUE TITLE
Pointers in xmas c++

### ISSUE THREAD

**Issue by gbonnema** [gbonnema/xmas#3]
Hey guys,

How do we treat pointers? Do we use straight pointers, or smart pointers?
How do smart pointers combine with qml and qtquick2?

**Comment by stefanXmas** [comment]
Guus ,

ik weet niet of dit je verder helpt , eerste 2 ivm qml vs smart pointers
(issues?), daarna 3 links ivm qml als uitbreiding op c++


http://qt-project.org/wiki/SharedPointersAndQmlOwnership

*"Currently, QML isn’t aware of QSharedPointer and friends, but internally
uses its own guard-types to react to QObject deletion. If you want to
ensure that the engine won’t delete the QObject you pass in, you need to
explicitly set the ownership of the QObject to CppOwnership (there’s a
QQmlEngine function to do so). Alternatively, if the QObject has a parent
(ownership parent) set, the engine won’t delete it"*

http://stackoverflow.com/questions/19402279/qml-cannot-assign-assign-shared-ptrtrack-to-unknown-property-type

*There is little point in passing a shared_ptr (or QSharedPointer) to QML,
thus the QML engine doesn't support it. QML supports a very limited list of
data types. If you're passing a pointer, it must be a naked pointer
to QObject.*

hieronder vind je info over wat wel en niet kan bij het combineren van een
specifiek c++ model met qml

http://hybridcoding.blogspot.be/2013/01/storing-visual-qml-item-qquickitems-in.html

nog beter is deze van Qt
http://doc.qt.io/qt-5/qtqml-cppintegration-interactqmlfromcpp.html

ftp://ftp.informatik.hu-berlin.de/pub/Linux/Qt/QT/videos/DevDays2011/TechnicalSessions/DevDays2011_-_Qt_Quick_Best_Practices_And_Design_Patterns.pdf


*mvg,*
*stefan*



2015-01-17 22:46 GMT+01:00 Guus <notifications@github.com>:
